"""Database models."""
from sqlalchemy import Column, Integer, String, Float, DateTime
from sqlalchemy.sql import func
from .database import Base

class Ticker(Base):
    """Represents a publicly traded company."""
    __tablename__ = "tickers"

    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String, unique=True, index=True)
    company_name = Column(String, index=True)
    market_cap = Column(Float, nullable=True) # in millions
    avg_volume = Column(Float, nullable=True)
    
    # Phonetic indexing
    phonetic_primary = Column(String, index=True)


class Brand(Base):
    """Represents an unlisted entity, product, or brand."""
    __tablename__ = "brands"

    id = Column(Integer, primary_key=True, index=True)
    brand_name = Column(String, unique=True, index=True)
    industry = Column(String, nullable=True)


class Alert(Base):
    """Represents an actionable alert generated by the system."""
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    ticker_symbol = Column(String, index=True)
    brand_name = Column(String, index=True)
    meme_score = Column(Float)
    volume_surge_multiplier = Column(Float)
    social_velocity = Column(Float)
    timestamp = Column(DateTime(timezone=True), server_default=func.now())
